fix: set executable bits after extracting
When building the `warc-indexer` docker image with the command below
`docker build . --tag indexer --file Dockerfile.warc-indexer`

and then using the built image to run `warc-indexer.sh` with the command
below `docker run --rm --tty --interactive indexer
/opt/warc-indexer/warc-indexer.sh`

you get the following error:

```
/__cacert_entrypoint.sh: line 30: /opt/warc-indexer/warc-indexer.sh:
Permission denied
```

After setting all executable bits for all `.sh` files the following
message is printed instead:

```
Error: No WARCs specified

For full usage information call

  ./warc-indexer -h
```

A regression test has been added.

Solves https://github.com/nlnwa/solrwayback-adaption/issues/21